# Generated by Django 5.2.1 on 2025-05-15 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("airport", "0003_alter_order_options_alter_airport_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="flight",
            name="crews",
            field=models.ManyToManyField(
                blank=True, related_name="flights", to="airport.crew"
            ),
        ),
    ]
