# Generated by Django 5.2.1 on 2025-05-15 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("airport", "0004_flight_crews"),
    ]

    operations = [
        migrations.AddField(
            model_name="crew",
            name="image",
            field=models.ImageField(null=True, upload_to="crew_image_upload"),
        ),
    ]
