# Generated by Django 5.2.1 on 2025-05-15 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("airport", "0005_crew_image"),
    ]

    operations = [
        migrations.RenameField(
            model_name="airplane",
            old_name="seat_in_row",
            new_name="seats_in_row",
        ),
    ]
